### ISSUE TITLE
watcher?

### ISSUE THREAD

**Issue by redpik** [danielhusar/grunt-pleeease#7]
Hi,
Is it possible to have an example with a watcher? For example it's really hard to write a Gruntfile with compass & watch.
I tried to make something and I have this sort of message:
```
Running "watch" task
Waiting...
Verifying property watch.pleeease.files exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch.pleeease.files" missing.
```
Thanx for your help.

**Comment by danielhusar** [comment]
Hey,

are you using `grunt-contrib-watch` ?
Because this should work out of the box.

`
watch: {
  scripts: {
    files: '**/*.css',
    tasks: ['pleeease'],
    options: {
      interrupt: true,
    },
  },
},
`

**Comment by redpik** [comment]
Hi Daniel,
thanx a lot for your quick answer. It works!!

Just one note, In the Gruntfile.js we can write:
```
		pleeease: {
			custom: {
				options: {
					config: '.pleeeaserc'
				},
				/* ... */
			}
		}
```
I think you have to put it in the doc.
Thanx again!

**Comment by danielhusar** [comment]
Hi,

yep good idea, I will add it, thanks.
